Second page
Detrut/Sedona pull request #3
Opened 2024-02-12 23:25 UTC by Detrut

2024-02-13 00:00 UTC, ArhyH commented on css/style.scss
> +}
title - это заглавие) про ссылку писал правку. Ссылка - это блок цссный link. В итоге будет link { &:hover {} &:active {} }

2024-02-13 00:22 UTC, ArhyH requested changes

2024-02-13 00:22 UTC, ArhyH commented on css/null_style.scss
> +img{vertical-align: top;}
Добавляй пустую строку в конце каждого файла. Теперь это удет делаться автоматически, так как ты добавил config

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                              <svg width="75" height="72" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M45.656 65.033h-16V41.21h16v23.823Zm-2.938-20.899H32.593V
Удали старые свг
Пережми все картинки в tinypng

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                              <svg width="75" height="72" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M45.656 65.033h-16V41.21h16v23.823Zm-2.938-20.899H32.593V
исправь табуляции в штмл файлах

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +    <div class="header__wrapper">
правки по хедеру в другом пуле

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +      <div class="wrapper">
правки по body в другом пуле

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                  <div class="about__images">
```suggestion
                  <div class="about__image">
```

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
title - это хаглавие. Используй правильные теги. Для заглавий испольщуются h1-h6

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
h2. например. Писал выше правку

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title content__title_width">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="title content__title_width">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                          <div class="content__text">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                      <div class="about__subtitle">
h2

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                      <div class="about__text about__text_width">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                <input type="text" id="forms__select" value="24 апреля 2017">
```
<label>
  <p>text</p>
  <input />
</label>
```

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                <label for="forms__select" class="forms__title">Дата выезда:</label>
та же исправь

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                  <div class="forms__title forms__title_margin-left">
h3

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <a href="#" class="forms__symbol">
button

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <div class="forms__text">
input

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <a href="#" class="forms__symbol">
button

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                  <div class="forms__title forms__title_margin-right">
h3

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <a href="#" class="forms__symbol">
button

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <div class="forms__text">
input

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                    <a href="#" class="forms__symbol">
button

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +                <a href="#" class="forms__button">
button type submit

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +          <div class="forms">
```suggestion
          <form class="forms">
```

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +    <div class="footer__wrapper">
та же история. перенеси класс на footer. назови его footer

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +          <div class="footer__subtitle">
p

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +          <div class="footer__subtitle">
a href="tel:phoneNumber"
https://developer.mozilla.org/ru/docs/Web/HTML/Element/a

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +        <div class="footer__wrapper-icons">
classname="socials" и дальше меняй. Моешь сделать список ссылок в nav

2024-02-13 00:22 UTC, ArhyH commented on index.html
> +          <a class="footer__text">
это classname="link"

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +          <a href="index.html">Информация</a>
идентично первой странице

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +      <div class="menu">
идентично первой странице

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <label for="checkbox-1" class="title title_white title_font-size">Бассейн</label>
заверни input в label и дай тексту отдельный тег

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <label for="checkbox-2" class="title title_white title_font-size">Парковка</label>
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <label for="checkbox-3" class="title title_white title_font-size">wi-fi</label>
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <label for="checkbox-5" class="title title_white title_font-size">Мотель</label>
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <label for="checkbox-6" class="title title_white title_font-size">Апартаменты</label>
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +            <div class="title title_white margin-bottom-15px">
h2

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +              <div class="menu__rate">
p

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +              <div class="menu__rate">
p

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +                <svg width="2" height="22" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h2v22H0z"/></svg>
херня, нарисуй полоску через псевдоэлемент

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +          <div class="title">
h3

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +          <div class="sorting__subtitle">
h4

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +          <a href="#" class="sorting__filter">По рейтингу</a>
button

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +      <div class="hotels">
используй другие теги кроме дивов. У тебя есть article, section

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +              </div>
```suggestion
              <div class="hotels__subtitle">
                <span>Гостиница</span>От 4000 Р.
              </div>
```
```suggestion
              <div class="hotels__subtitle">
                <span class="someClassname">Гостиница</span>
                <span class="someClassname">От 4000 Р.</span>
              </div>
```

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +            <div class="hotels__rate">
p

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +              </div>
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +              <div class="hotels__buttons">
идентично

2024-02-13 00:22 UTC, ArhyH commented on second_page.html
> +      <div class="footer__container">
правки по футеру, как на первой странице

2024-02-13 04:05 UTC, ArhyH requested changes

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  height: 33.3333%;
отстань от ширины, она не нужна каждому блоку. дай им споконо жить самостоятельно

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  height: 90px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  width: 177px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  letter-spacing: 0px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  width: 250px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  height: 27px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  letter-spacing: 0.5px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  color: white;
hex

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  height: 27px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  letter-spacing: 0.5px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  margin-right: 90px;
высота и отступ

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  padding: 0 5px;
💩 , скорее всего

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  height: 27px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +  letter-spacing: 0.5px;
💩

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +input[type="range"] {
класс

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +input[type="range"]::-webkit-slider-thumb {
класс плюс ::lalala

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +input[type=range]::-webkit-slider-runnable-track  {
класс + ::lalala

2024-02-13 04:05 UTC, ArhyH commented on css/style.scss
> +.about__background  {
Теперь поиграем в цсс модули. Правила следующие: 1 бэи блок = его жлементы и модификаторы = 1 цсс модуль. Создаешь папку modules. В ней хранишь все файлы модулей. Файлы модулей импортируешь в файл main.scss, который тоже лежит в папке modules. main.scss импортируешь в файл style.scss. 
Стили из одного модуля нельзя импортировать в другой модуль. Внутри одного модуля хранятся стили только для 1 Бэм блока

2024-02-15 20:47 UTC, ArhyH requested changes

2024-02-15 20:47 UTC, ArhyH commented on css/null_style.css
> +}
можно удалить)

2024-02-15 20:47 UTC, ArhyH commented on css/null_style.css
> +}
пустая строка

2024-02-15 20:47 UTC, ArhyH commented on css/null_style.scss
> +    //height: 100%;
коменты удаляй

2024-02-15 20:47 UTC, ArhyH commented on css/null_style.scss
> +img{vertical-align: top;}
правильное форматирование

2024-02-15 20:47 UTC, ArhyH commented on css/style.scss
> +}
картинку правильно назови img/Shape (1).png

2024-02-15 20:47 UTC, ArhyH commented on css/style.scss
> +}
иконки минуса и плюса тоже нормально назови

2024-02-15 20:47 UTC, ArhyH commented on css/style.scss
> +}
другиее тоже переименуй. удаляй svgrepo

2024-02-15 20:47 UTC, ArhyH commented on index.html
> +        <li class="header__item">
неправильная расстановка бэм блоков. header > link > header. link__list нужно переименовать в блок хедера

2024-02-15 20:47 UTC, ArhyH commented on index.html
> +          <img src="img/bridge.png" alt="" width="66.6666%" height="100%"/>
такие проценты непонятные. выглядит как пальцем в небо. заверни какртинку в какой-то див и дай ему понятную ширину. раздели пространство через флексы и тд

2024-02-15 20:47 UTC, ArhyH commented on index.html
> +      <form class="form">
заверни форму в див, на котором будут висеть стили для позиционирования и размеров, если они у тебя есть. Подсказка - это будет компонент dialog

2024-02-15 20:47 UTC, ArhyH commented on modules/about.scss
> +    letter-spacing: 0px;
удали, правка уже была

2024-02-15 20:47 UTC, ArhyH commented on modules/about.scss
> +    width: 1200px;
на эту ширину была правка, удаляй

2024-02-15 20:47 UTC, ArhyH commented on modules/about.scss
> +    width: 500px;
уже была правка

2024-02-15 20:47 UTC, ArhyH commented on modules/about.scss
> +    width: 1200px;
body 1280, почему тут 1200?

2024-02-15 20:47 UTC, ArhyH commented on modules/button.scss
> +  &.button__sorting {
как-то странно это выглядит. Это будето ребенок кнопки, но он должен быть в комбе с основным классом button. Если это модификатор, то выглядит плохо. button--type--sortings

2024-02-15 20:47 UTC, ArhyH commented on modules/button.scss
> +    display: flex;
флексовые свойства повторяются в этих штуках для кнопки, оптимизируй код и вынеси повторяющиеся стили в обычный класс button

2024-02-15 20:47 UTC, ArhyH commented on modules/checkbox.scss
> +    letter-spacing: 0px;
Зачем тебе letterspacing?

2024-02-15 20:47 UTC, ArhyH commented on modules/content.scss
> +    flex-direction: row;
она по дефолту row

2024-02-15 20:47 UTC, ArhyH commented on modules/content.scss
> +    height: 256px;
выысоту сделай паддингами

2024-02-15 20:47 UTC, ArhyH commented on modules/content.scss
> +    flex-direction: row;
это дефолтное значение

2024-02-15 20:47 UTC, ArhyH commented on modules/content.scss
> +    height: 256px;
отступами

2024-02-15 20:47 UTC, ArhyH commented on modules/footer.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/footer.scss
> +  &__icon {
s?

2024-02-15 20:47 UTC, ArhyH commented on modules/footer.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +  background-color: rgb(255, 255, 255);
по поводу этого писал правку про dialog

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +  &__button {
почему не БЭМ button?

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +    width: 110px;
ширина у текста - фу. Зачем?

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +    &_padding-left-30px {
писал про такие модификаторы в прошлой итерации правок

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/form.scss
> +    padding-left: 16px;
выглядит не очень

2024-02-15 20:47 UTC, ArhyH commented on modules/header.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/header.scss
> +  &__logo{
пробел перед скобкой

2024-02-15 20:47 UTC, ArhyH commented on modules/header.scss
> +    margin-top: 10px;
используй селекторы с +

2024-02-15 20:47 UTC, ArhyH commented on modules/hotels.scss
> +.hotels{
пробел перед скобкой

2024-02-15 20:47 UTC, ArhyH commented on modules/hotels.scss
> +    margin-left: 30px;
+

2024-02-15 20:47 UTC, ArhyH commented on modules/hotels.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/hotels.scss
> +    margin-right: 90px;
+

2024-02-15 20:47 UTC, ArhyH commented on modules/hotels.scss
> +    letter-spacing: 0.5px;
💩 💩 💩

2024-02-15 20:47 UTC, ArhyH commented on modules/info.scss
> +  &__button {
Почему не БЭМ button?

2024-02-15 20:47 UTC, ArhyH commented on modules/info.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/link.scss
> +  &__list {
Это другой БЭМ блок

2024-02-15 20:47 UTC, ArhyH commented on modules/link.scss
> +  letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +  &__button {
БЭМ блок

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +  &__submit {
БЭМ блок

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +    &:hover{
паддинг перед скобкой

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +    height: 38px;
Ставлю, что можно отступами

2024-02-15 20:47 UTC, ArhyH commented on modules/menu.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/range.scss
> +.range[type="range"] {
type теперь добавлять не обязательно

2024-02-15 20:47 UTC, ArhyH commented on modules/range.scss
> +  }
зачем? можно без & в стили для класса

2024-02-15 20:47 UTC, ArhyH commented on modules/separator.scss
> +    border-bottom: 24px solid #ffffff;
что за дичь? это должна быть 1 пиксельная шляпа, которая делает поолску. ЧТо ты с ней сотворил?

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +  height: 86px;
отступы

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +    width: 50%;
лишнее. Ты все еще ограничиваешь блоки размерами, когда они должны сами такими становиться из-за других стилей

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +    margin-right: 90px;
+

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +    padding: 5px;
+ и отступ перед скобкой на селекторе

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +  &__filter{
отступы перед скобками

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +    &:hover{
скобка

2024-02-15 20:47 UTC, ArhyH commented on modules/sorting.scss
> +    letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/title.scss
> +  letter-spacing: 0px;
💩

2024-02-15 20:47 UTC, ArhyH commented on modules/title.scss
> +  }
сам тайтл не интерактивный элемент. Это просто текст. Сделал что-то криво. Перенеси на правильный элемент.сделай через правильный элемент

2024-02-15 20:47 UTC, ArhyH commented on modules/title.scss
> +  &_subtitle {
title_subtitle? 💩

2024-02-15 20:47 UTC, ArhyH commented on second_page.html
> +          <div class="menu__checkboxs">
checkboxes

2024-02-15 20:47 UTC, ArhyH commented on second_page.html
> +            <h1 class="title title_subtitle">Тип жилья:</h1>
это ссылка, а не текст

2024-02-15 20:47 UTC, ArhyH commented on second_page.html
> +            <h1 class="title title_subtitle">Тип жилья:</h1>
давай интерактив тексту - плохая практика

2024-02-15 20:47 UTC, ArhyH commented on second_page.html
> +            <img src="img/hotel2.png" alt="" width="135" height="90"/>
заполни альты картинкам. у всех картинок должно быть описание

2024-02-15 20:47 UTC, ArhyH commented on second_page.html
> +            <a href="#" class="link title title-hover title-active">
мы с тобой не обсуждали комбинирование БЭМ блоков. Это устаревшая практика. выкручивайся через link

2024-02-15 21:34 UTC, ArhyH commented on modules/content.scss
> +  &__card {
Давай сделаем новый БЭМ блок content-card
title с модификатором ширины пусть станет content-card__title сразу с шириной

2024-02-15 21:59 UTC, ArhyH commented on modules/form.scss
> +    padding-left: 16px;
кнопка - это кастомная иконка для инпута. У нее должны быть состояния. Когда ховер на инпуте - иконка перекрашивается. Правым паддингном ограничь область, чтобы на иконку не мог звйти текст. Для инпута type date

2024-02-15 22:21 UTC, ArhyH commented on modules/sorting.scss
> +  border-bottom: 1px solid #33333348;
убери паддинг с filters и margin с icons  и дай сюда горизонтальные паддинги

2024-02-15 22:21 UTC, ArhyH commented on second_page.html
> +            <h1 class="title title_subtitle">Инфраструктура:</h1>
fieldsset
legend 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

2024-02-18 16:48 UTC, Detrut commented on modules/header.scss
> +    margin-top: 10px;
Обсудили отдельно: отказались от этой правки.

2024-02-18 17:01 UTC, Detrut commented on modules/sorting.scss
> +    margin-right: 90px;
Не имело смысла, т.к. там элементы вложены.

2024-02-18 17:04 UTC, Detrut commented on modules/content.scss
> +  &__card {
Использовал другое решение.

2024-02-18 17:04 UTC, Detrut commented on modules/form.scss
> +    padding-left: 16px;
Использовал стандартные свойства для иконки, убрав кнопку.

2024-02-18 19:27 UTC, ArhyH approved these changes

2024-02-18 19:28 UTC, merged